IDX_TO_JFT_EDIT_PROMPT_DICT = {
    'match' : {
        0   : 'a dog',
        1   : 'a person',
        2   : 'a photo of a bird',
        3   : 'a cake',
        4   : 'a horse',
        5   : 'a photo of a dog',
        6   : 'a red car',
        7   : 'a banana',
        8   : 'a photo of a beach',
        9   : 'a photo of a cake',
        10  : 'a photo of a cat',
        11  : 'a kitten',
        12  : 'a cat',
        13  : 'a horse',
        14  : 'two parrots',
        15  : 'a photo of a red shirt',
        16  : 'a photo of dog',
        17  : 'two pelicans',
    },
    'edit' : {
        0   : 'a jumping dog',
        1   : '', # 'a person with a crossed arms',
        2   : '', # 'a photo of a bird spreading wings',
        3   : 'a strawberry cake',
        4   : '', # 'a horse raising its head',
        5   : 'a photo of a sitting dog',
        6   : 'a sports car',
        7   : 'two bananas',
        8   : '', # 'a photo of a beach at night',
        9   : 'a photo of a birthday cake',
        10  : '', # 'a photo of a cat yawning',
        11  : '', # 'a kitten laying down',
        12  : 'a cat wearing a hat',
        13  : 'a zebra',
        14  : '', # 'two parrots looking down',
        15  : '', # 'a photo of a yellow shirt',
        16  : '', # 'a photo of jumping dog',
        17  : '', # 'two pelicans kissing',
        18  : 'a guitar',
        19  : 'a waffle with a wipped cream',
        20  : 'a basketball',
        21  : 'a photo of a tree in snow',
        22  : 'a wooden chair',
        23  : 'a painted easter egg',
    },
}

IDX_TO_LANDSCAPE_EDIT_PROMPT_DICT = {
    'match' : 'a landscape',
    'edit'  : 'a cyberpunk landscape',
}
IDX_TO_WALLPAPER_EDIT_PROMPT_DICT = {
    'match' : 'a wallpaper',
}
IDX_TO_RANDOM_EDIT_PROMPT_DICT = {
    'match' : 'a dog',
    'edit'  : 'a jumping dog',
}